spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinematica
    username: cinematica
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  bucket:
    name: cinematica


cloud:
  aws:
    credentials:
      access-key: AKIAW3MEFBHYBMEYF2NG
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false



server:
  port: 8081